### ISSUE TITLE
UI: Transition animation not visible anymore in the new theme

### ISSUE THREAD

**Issue by atteggiani** [ACCESS-NRI/access-hive-forum-theme#17]
In the old theme in dark mode (in light mode is present but not visible) there is a transition animation for a highlighted topic (for example when opening up a direct link to a topic) consisting of a blue-ish background fading-in.
The animation looks like the following from [this link](https://forum.access-hive.org.au/t/xarray-warnings-while-loading-data-using-cosima-cookbook/2169/7):

https://github.com/user-attachments/assets/b7036bfd-c240-4e49-9413-3203595b15c1

The implementation that renders the animation for the class `.topic-body.highlighted` is the following (from a default discourse script I suppose):
```scss
@media (prefers-reduced-motion: no-preference) {
  .topic-body.highlighted,
  .small-action-desc.highlighted {
    animation: background-fade-highlight 2.5s ease-out;
  }
  // Disable animation so deleted status is visible immediately
  .deleted .topic-body.highlighted {
    animation: none;
  }
}
```

In the new theme, this animation is not rendered anymore. 
I suppose this happens because the `background-color` of a post has been overwritten to a specific colour via this snippet found in the new theme:

```scss
.topic-body {
  background-color: var(--custom-text_background) !important;
  border: 2px solid var(--primary-low) !important;
  border-radius: var(--large-border-radius);
}
```
I haven't tested it, and I am not sure this is the actual reason behind the missing amimation. 

I would say:
- [ ] The animation should be reinstated
- [ ] Even if that part of the snippet was not really the cause of the issue, I don't think the ` background-color: var(--custom-text_background) !important;` line should be there, as it doesn't seem to add any rendering feature.
